### ISSUE TITLE
MongoError: Cannot use (or request) retryable writes with multi=true

### ISSUE THREAD

**Issue by juancarlosfarah** [chili-epfl/FROG#1238]
I'm having an issue starting up the app using `retryWrites=true`. Have you experiences this before?

It looks like an issue with me using retryable writes and something using `multi-true`.

```
=> Starting meteor app on port:80
	Meteor settings { public:
	   { sharedburl: 'wss://<DOMAIN>:3002',
	     friendlyProduction: true },
	  sharedb_dburl: 'mongodb://<USER>:<PW>@<HOSTS>/<DB>?ssl=true&replicaSet=staging-shard-0&authSource=admin&retryWrites=true' }
	(node:1) Warning: N-API is an experimental feature and could change at any time.
	Running shareDB server

	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	MongoError: Cannot use (or request) retryable writes with multi=true
	    at Function.MongoError.create (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:45:10)
	    at toError (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:149:22)
	    at /built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1029:39
	    at handler (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1209:22)
	    at /built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:544:18
	    at _combinedTickCallback (internal/process/next_tick.js:131:7)
	    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

	=> Redeploying previous version of the app


	      ------------------------------------STDOUT------------------------------------
	      => Container status:
	restarted: 10 times {"Bridge":"","SandboxID":"fc3786651310bcb259029bbce37c47c4b58cdc4cbe9efca8108b1bf65b51f01a","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/default","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"host":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"c471fffab949412415c47efab7acda98e598a4b4bc42aae78831122cb7bcd8c9","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":1,"Error":"","StartedAt":"2018-07-26T15:41:28.175520251Z","FinishedAt":"2018-07-26T15:41:30.488650987Z"}
	=> Logs:

	To see more logs type 'mup logs --tail=200'
```

I'm going to try and fix it on my end, but just in case, I wanted to post it here in case you want to have a look as well.

**Comment by houshuang** [comment]
Seems like this has been fixed, and will be merged in a version coming soon. https://github.com/meteor/meteor/issues/10087
