### ISSUE TITLE
Dashboard subscription problem

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1555]
Saw this in the server logs
```
159.69.208.4]2018-12-09T07:06:55.750158191Z Exception in callback of async function: TypeError: Cannot read property 'ready' of undefined
[159.69.208.4]2018-12-09T07:06:55.750319314Z     at server/dashboardSubscription.js:26:31
[159.69.208.4]2018-12-09T07:06:55.750324831Z     at Object.keys.forEach.name (server/dashboardSubscription.js:132:19)
[159.69.208.4]2018-12-09T07:06:55.750328320Z     at Array.forEach (<anonymous>)
[159.69.208.4]2018-12-09T07:06:55.750336516Z     at archiveDashboardState (server/dashboardSubscription.js:115:34)
[159.69.208.4]2018-12-09T07:06:55.750339884Z     at loop (server/redis.js:25:5)
[159.69.208.4]2018-12-09T07:06:55.750343111Z     at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by houshuang** [comment]
Looks like this was right after server was initialized.
