### ISSUE TITLE
Missing modules 

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#757]
This is the first time I've seen this error. Does anyone have an idea of its symptoms and how to fix it? 

is something that is happening at the initial_setup process? 

@Meteor startup: 

Unable to resolve some modules:

  "bufferutil" in                             
/Users/user/dev/CK-FROG/frog/node_modules/ws/lib/BufferUtil.js (os.osx.x86_64)
  "utf-8-validate" in                         
/Users/user/dev/CK-FROG/frog/node_modules/ws/lib/Validation.js (os.osx.x86_64)
  "hiredis" in                                
/Users/user/dev/CK-FROG/frog/node_modules/redis-parser/lib/hiredis.js
(os.osx.x86_64)
                  
@watch_run

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
module.js:544
    throw err;

**Comment by houshuang** [comment]
@aperritano Did you resolve? Cannot reproduce.

**Comment by aperritano** [comment]
The solution was to clear the cache and reinstall node. Making sure it is the latest version.
