### ISSUE TITLE
Engine flow bug

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#84]
I found this error in my console after playing with pull request #80:

```
I20170222-10:51:46.285(1)? Exception while invoking method 'next.activity' TypeError: Cannot read property '_id' of undefined
I20170222-10:51:46.322(1)?     at [object Object].Meteor.methods.next.activity (imports/api/engine.js:38:40)
I20170222-10:51:46.323(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170222-10:51:46.345(1)?     at packages/ddp-server/livedata_server.js:719:19
I20170222-10:51:46.366(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170222-10:51:46.373(1)?     at packages/ddp-server/livedata_server.js:717:40
I20170222-10:51:46.373(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170222-10:51:46.403(1)?     at packages/ddp-server/livedata_server.js:715:46
I20170222-10:51:46.405(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
I20170222-10:51:46.405(1)?     at packages/ddp-server/livedata_server.js:559:43
```

I think I might have clicked next while in a session that has no activity, or when in a session with activities, but before pressing start.

Either way, we should check this, and disable the next button etc, rather than letting this JS runtime error occur.

**Comment by lfaucon** [comment]
This bug is likely outdated, now that the method `next.activity` has been rewritten for the compound activities
